import React from 'react'

export const About = () => (
    <div>
         <h2>About</h2>
         <p>This is about us.</p>   
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In fermentum posuere urna nec tincidunt praesent semper feugiat. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Et pharetra pharetra massa massa ultricies mi. Quis auctor elit sed vulputate mi sit amet. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in. Non tellus orci ac auctor augue mauris augue. Faucibus pulvinar elementum integer enim neque volutpat. Urna porttitor rhoncus dolor purus non enim. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Integer eget aliquet nibh praesent. Gravida cum sociis natoque penatibus et magnis dis. Semper eget duis at tellus at. Felis donec et odio pellentesque. Neque aliquam vestibulum morbi blandit cursus risus at. Vulputate mi sit amet mauris commodo. In eu mi bibendum neque egestas congue.</p>   
         <p>Tempus quam pellentesque nec nam aliquam sem et tortor. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Semper auctor neque vitae tempus quam pellentesque. Nec dui nunc mattis enim ut. Suspendisse in est ante in nibh mauris cursus mattis. Vitae nunc sed velit dignissim sodales ut. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Molestie a iaculis at erat pellentesque adipiscing. Risus commodo viverra maecenas accumsan. Tellus at urna condimentum mattis pellentesque id nibh tortor. Tortor id aliquet lectus proin nibh nisl. Netus et malesuada fames ac turpis egestas. Neque egestas congue quisque egestas. Congue nisi vitae suscipit tellus. Non nisi est sit amet facilisis magna. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet.</p>   
         <p>Tempus quam pellentesque nec nam aliquam sem et tortor. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Semper auctor neque vitae tempus quam pellentesque. Nec dui nunc mattis enim ut. Suspendisse in est ante in nibh mauris cursus mattis. Vitae nunc sed velit dignissim sodales ut. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Molestie a iaculis at erat pellentesque adipiscing. Risus commodo viverra maecenas accumsan. Tellus at urna condimentum mattis pellentesque id nibh tortor. Tortor id aliquet lectus proin nibh nisl. Netus et malesuada fames ac turpis egestas. Neque egestas congue quisque egestas. Congue nisi vitae suscipit tellus. Non nisi est sit amet facilisis magna. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet.</p>   
    </div>
);
